name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 
        with:
          heroku_email: "w.vangils2@student.avans.nl"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"